# Generated by Django 5.0.1 on 2025-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="questionset",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="questionset",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
